### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PattoMotto** [PattoMotto/uWall#2]
- [x] **BUG** timer reset when app launch
- [ ] download button
- [ ] switch change home / home + lock screen
- [ ] add new image source https://pixabay.com/api/docs/
